config/routes.rb
Rails.application.routes.draw do
	root 'posts#index', as: 'home'

	get 'about' => 'pages#about'

	resources :posts do
		resources :comments
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = Comment.all
		@comment.each do |com|
			com.destroy
		end

		redirect_to post_path
	end

	private def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "112",
		except: [:index, :show]

	def index 
		@post = Post.all
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		# render plain: params[:post].inspect
		@post = Post.new(post_params)

		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	def destroy
		@post = Post.find(params[:id])

		@post.destroy
		redirect_to home_path
	end

	def update
		@post = Post.find(params[:id])

		if(@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

	private def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apptest</title>
    <%= csrf_meta_tags %>
	
	<%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
	  <h5 class="my-0 mr-md-auto font-weight-normal">Test App</h5>
	  <nav class="my-2 my-md-0 mr-md-3">
	    <span class="p-2 text-dark" href="#"><%= link_to "Main page", home_path %></span>
	    <span class="p-2 text-dark" href="#"><%= link_to "About us", about_path %></span>
	  </nav>
	  <span class="btn btn-outline-primary"><%= link_to "New post", new_post_path %></span>
	</div>
	
	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4>About us</h4>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		Name <br>
		<%= f.text_field :title, {:class => 'form-control'} %>
	</p>
	<p>
		Text <br>
		<%= f.text_area :body, {:class => 'form-control'} %>
	</p>
	<p>
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/posts/index.html.erb
<h3>All our Posts</h3>
<% @post.each do |post| %>
	<div class="alert alert-light">
		<h3><%= post.title %></h3>
		<p><%= post.body %></p>
		<%= link_to "Read more", post_path(post), :class => 'btn btn-outline-primary' %>
	</div>
<% end %>

app/views/posts/new.html.erb
<h2>Add new Post</h2>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		Name <br>
		<%= f.text_field :title, {:class => 'form-control'} %>
	</p>
	<p>
		Text <br>
		<%= f.text_area :body, {:class => 'form-control'} %>
	</p>
	<p>
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to 'Edit', edit_post_path(@post), :class => "btn btn-warning" %>
<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are U sure?'}, :class => "btn btn-danger" %>
<hr>
	<h2>All comments</h2>
<% @post.comments.each do |comment| %>
	<div class="alert alert-light">
		<p><strong><%= comment.username %></strong>: <%= comment.body %>  <%= link_to 'Delete', post_comment_path(@post), method: :delete %></p>
		
	</div>
<% end %>
<hr>
<h2>Add new Comment</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		User name <br>
		<%= f.text_field(:username, {:class => 'form-control'}) %>
	</p>
	<p>
		Text <br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.submit("Add new coment", {:class => 'btn btn-warning'}) %>
	</p>
<% end %>